version: '3.8'

services:
  db:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: mysql@frank
      MYSQL_DATABASE: videos_db
      MYSQL_USER: frank
      MYSQL_PASSWORD: frank@frank
    ports:
      - "6033:3306"
    volumes:
      - /Users/frank/Documents/GitHub-Docker/mysql-server/dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    links:
      - db
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
volumes:
  dbdata:
